run:
   @echo -e "\n[[ Build ]]\n"
   zig build --summary all
   @echo -e "\n[[ Run ]]\n"
   time ./zig-out/bin/bonita-prototype

walk *FLAGS:
   @echo -e "\n[[ Build ]]\n"
   zig build --summary all
   @echo -e "\n[[ Run ]]\n"
   time ./zig-out/bin/bonita-prototype {{FLAGS}}

serve-site:
   http-server sandbox/site -p 1111

serve-dist:
   http-server sandbox/dist -p 2222